export const NAV_SHOW = 'NAV_SHOW'
export const NAV_HIDDEN = 'NAV_HIDDEN'
export const AD_SHOW = 'AD_SHOW'
export const AD_HIDDEN = 'AD_HIDDEN'
export const AD_DISPLAY = 'AD_DISPLAY'
export const MENU_SHOW = 'MENU_SHOW'
export const MENU_HIDDEN = 'MENU_HIDDEN'
